/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDispositivosRouteImport } from './routes/_authenticated/dispositivos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPlantasPlantIdRouteImport } from './routes/_authenticated/plantas.$plantId'
import { Route as ApiDeviceReadingRouteImport } from './routes/api/device/reading'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicDeviceReadingRouteImport } from './routes/api/public/device/reading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDispositivosRoute =
  AuthenticatedDispositivosRouteImport.update({
    id: '/dispositivos',
    path: '/dispositivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantasPlantIdRoute =
  AuthenticatedPlantasPlantIdRouteImport.update({
    id: '/plantas/$plantId',
    path: '/plantas/$plantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiDeviceReadingRoute = ApiDeviceReadingRouteImport.update({
  id: '/api/device/reading',
  path: '/api/device/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceReadingRoute = ApiPublicDeviceReadingRouteImport.update({
  id: '/api/public/device/reading',
  path: '/api/public/device/reading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/plantas/$plantId': typeof AuthenticatedPlantasPlantIdRoute
  '/api/device/reading': typeof ApiDeviceReadingRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/device/reading': typeof ApiPublicDeviceReadingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/plantas/$plantId': typeof AuthenticatedPlantasPlantIdRoute
  '/api/device/reading': typeof ApiDeviceReadingRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/device/reading': typeof ApiPublicDeviceReadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dispositivos': typeof AuthenticatedDispositivosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/plantas/$plantId': typeof AuthenticatedPlantasPlantIdRoute
  '/api/device/reading': typeof ApiDeviceReadingRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/device/reading': typeof ApiPublicDeviceReadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dispositivos'
    | '/painel'
    | '/plantas/$plantId'
    | '/api/device/reading'
    | '/api/public/ingest'
    | '/api/public/device/reading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dispositivos'
    | '/painel'
    | '/plantas/$plantId'
    | '/api/device/reading'
    | '/api/public/ingest'
    | '/api/public/device/reading'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dispositivos'
    | '/_authenticated/painel'
    | '/_authenticated/plantas/$plantId'
    | '/api/device/reading'
    | '/api/public/ingest'
    | '/api/public/device/reading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiDeviceReadingRoute: typeof ApiDeviceReadingRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicDeviceReadingRoute: typeof ApiPublicDeviceReadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dispositivos': {
      id: '/_authenticated/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof AuthenticatedDispositivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantas/$plantId': {
      id: '/_authenticated/plantas/$plantId'
      path: '/plantas/$plantId'
      fullPath: '/plantas/$plantId'
      preLoaderRoute: typeof AuthenticatedPlantasPlantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/device/reading': {
      id: '/api/device/reading'
      path: '/api/device/reading'
      fullPath: '/api/device/reading'
      preLoaderRoute: typeof ApiDeviceReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/reading': {
      id: '/api/public/device/reading'
      path: '/api/public/device/reading'
      fullPath: '/api/public/device/reading'
      preLoaderRoute: typeof ApiPublicDeviceReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDispositivosRoute: typeof AuthenticatedDispositivosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPlantasPlantIdRoute: typeof AuthenticatedPlantasPlantIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDispositivosRoute: AuthenticatedDispositivosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPlantasPlantIdRoute: AuthenticatedPlantasPlantIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiDeviceReadingRoute: ApiDeviceReadingRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicDeviceReadingRoute: ApiPublicDeviceReadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
